import { defineMiddleware } from "astro:middleware";
import { createSupabaseClient } from "./lib/supabase";

// In production, CSP is generated by Astro (security.csp in astro.config.mjs)
// and emitted as a <meta http-equiv="content-security-policy"> tag, so that
// SHA-256 hashes for Astro's inline island-hydration scripts are included
// automatically. A stricter response-header CSP would override that meta tag
// and break hydration, so the middleware no longer sets a prod CSP header.
//
// In dev, Astro's CSP is disabled (Vite dev server), so we still ship a dev
// CSP header here — it adds 'unsafe-inline' to script-src (Astro's dev
// toolbar emits an inline bootstrap that hydration cascades off of) and
// 'ws:' / 'localhost:*' to connect-src for Vite HMR.
const DEV_CSP =
  "default-src 'self'; script-src 'self' 'unsafe-inline' https://static.cloudflareinsights.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self' ws: http://localhost:* https://*.supabase.co https://cloudflareinsights.com; frame-ancestors 'none'; base-uri 'self'; form-action 'self'";

const SECURITY_HEADERS_BASE: Record<string, string> = {
  "X-Content-Type-Options": "nosniff",
  "X-Frame-Options": "DENY",
  "Referrer-Policy": "strict-origin-when-cross-origin",
  "Permissions-Policy": "camera=(), microphone=(), geolocation=()",
  "Strict-Transport-Security": "max-age=31536000; includeSubDomains",
};

export const onRequest = defineMiddleware(async (context, next) => {
  try {
    const supabase = createSupabaseClient(context);
    const {
      data: { session },
    } = await supabase.auth.getSession();
    context.locals.supabase = supabase;
    context.locals.session = session;
  } catch (e) {
    context.locals.startupError = e instanceof Error ? e.message : String(e);
  }

  const response = await next();

  for (const [key, value] of Object.entries(SECURITY_HEADERS_BASE)) {
    response.headers.set(key, value);
  }
  if (import.meta.env.DEV) {
    response.headers.set("Content-Security-Policy", DEV_CSP);
  }

  return response;
});
